# Generated by Django 6.0.1 on 2026-04-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.ImageField(default='', upload_to='image')),
            ],
        ),
    ]
