# Generated by Django 6.0.1 on 2026-04-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0003_addcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcourse',
            name='coursetypes',
            field=models.CharField(default='', max_length=50),
        ),
    ]
