# Generated by Django 6.0.1 on 2026-04-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0004_addcourse_coursetypes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addcourse',
            new_name='course',
        ),
    ]
