# Generated by Django 6.0.1 on 2026-04-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0011_elearning_users_school_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearning_users',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='elearning_users',
            name='confirm_password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
